### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'EdgeView' and 'list'

### ISSUE THREAD

**Issue by miguelwon** [benedekrozemberczki/LabelPropagation#3]
Hi,
I had this error with a fresh install and using your ``politician_edges.csv``as a testing example.

```
(env) mwon@mwon:/disk2/MP2Vec/LabelPropagation/src$ python label_propagation.py --input ../data/politician_edges.csv --seed 10 
+-------------------+------------------------------+
|     Parameter     |            Value             |
+===================+==============================+
| Assignment output | ./output/politician.json     |
+-------------------+------------------------------+
| Input             | ../data/politician_edges.csv |
+-------------------+------------------------------+
| Rounds            | 30                           |
+-------------------+------------------------------+
| Seed              | 10                           |
+-------------------+------------------------------+
| Weighting         | overlap                      |
+-------------------+------------------------------+
Traceback (most recent call last):
  File "label_propagation.py", line 17, in <module>
    create_and_run_model(args)
  File "label_propagation.py", line 11, in create_and_run_model
    model = LabelPropagator(graph, args)
  File "/disk2/MP2Vec/LabelPropagation/src/model.py", line 27, in __init__
    self.weight_setup(args.weighting)
  File "/disk2/MP2Vec/LabelPropagation/src/model.py", line 35, in weight_setup
    self.weights  = overlap_generator(overlap, self.graph)
  File "/disk2/MP2Vec/LabelPropagation/src/calculation_helper.py", line 53, in overlap_generator
    edges = edges + [(edge[1], edge[0]) for edge in edges]
TypeError: unsupported operand type(s) for +: 'EdgeView' and 'list'
```

**Comment by benedekrozemberczki** [comment]
Networkx version.

**Comment by miguelwon** [comment]
Ok and which networkx version should I use? I had this problem with a fresh instalation, including the needed packages list.

**Comment by benedekrozemberczki** [comment]
1.11
